name: CI

on:
  push:
    branches-ignore: [ 'main', 'doc/*' ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run lint script
      run: |
        cd backend
        ./lint.sh
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0
    needs: lint
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install reportgenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Restore dependencies
      run: dotnet restore backend/AuthServer.sln
    
    - name: Run test script
      run: |
        cd backend
        ./test.sh
  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME  }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        platforms: linux/amd64,linux/arm64
        push: true
        tags: brian861105/authserver:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max